# Generated by Django 5.0.2 on 2024-03-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher1',
            new_name='Teacher',
        ),
    ]
