# Generated by Django 5.0.2 on 2024-03-30 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0002_algorithm_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='student_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
