# Generated by Django 5.0.2 on 2024-03-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0003_class_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
