# Generated by Django 5.0.2 on 2024-03-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0003_remove_class_module_id_module_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='year_id',
        ),
        migrations.RemoveField(
            model_name='term',
            name='term_number',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
