# Generated by Django 5.0.2 on 2024-03-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0004_role_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=10, null=True),
        ),
    ]
