# Generated by Django 5.0.2 on 2024-03-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0006_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
    ]
