# Generated by Django 5.0.2 on 2024-03-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0007_remove_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=10, null=True),
        ),
    ]
