# Generated by Django 5.0.2 on 2024-03-30 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0010_alter_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
