# Generated by Django 5.0.2 on 2024-03-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0010_language_term_class_language_module_alter_class_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
