# Generated by Django 5.0.2 on 2024-03-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0011_alter_language_name_alter_term_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='class_id',
        ),
        migrations.AddField(
            model_name='class',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_database.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
