# Generated by Django 5.0.2 on 2024-03-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0012_remove_module_class_id_class_module_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='module_id',
            new_name='module',
        ),
    ]
