# Generated by Django 5.0.2 on 2024-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0012_itemtype_remove_algorithm_module_item_algorithm_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'ItemType', 'verbose_name_plural': 'ItemTypes'},
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
