# Generated by Django 5.0.2 on 2024-04-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0013_alter_itemtype_options_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
