# Generated by Django 5.0.2 on 2024-03-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0013_rename_module_id_class_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_database.class'),
        ),
    ]
