# Generated by Django 5.0.2 on 2024-03-17 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0014_remove_class_module_module_parent_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_database.language'),
        ),
    ]
