# Generated by Django 5.0.2 on 2024-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0014_remove_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
