# Generated by Django 5.0.2 on 2024-04-11 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0015_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField(default=100000)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
