# Generated by Django 5.0.2 on 2024-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0015_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='answers',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='hints',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='lines',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
