# Generated by Django 5.0.2 on 2024-04-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0016_algorithm_answers_algorithm_hints_algorithm_lines_and_more'),
        ('_database', '0016_group_module_order'),
    ]

    operations = [
    ]
