# Generated by Django 5.0.2 on 2024-04-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0017_merge_20240412_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
