# Generated by Django 5.0.2 on 2024-04-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0017_merge_20240412_1444'),
        ('_database', '0018_delete_group'),
    ]

    operations = [
    ]
