# Generated by Django 5.0.2 on 2024-04-19 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0020_studentalgorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentalgorithm',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
