# Generated by Django 5.0.2 on 2024-04-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0021_alter_studentalgorithm_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentalgorithm',
            old_name='algorithm_id',
            new_name='algorithm',
        ),
        migrations.RenameField(
            model_name='studentalgorithm',
            old_name='student_id',
            new_name='student',
        ),
    ]
