# Generated by Django 5.0.2 on 2024-04-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0022_rename_algorithm_id_studentalgorithm_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_database.item'),
        ),
        migrations.AlterField(
            model_name='page',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_database.item'),
        ),
    ]
