# Generated by Django 5.0.2 on 2024-04-20 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0023_alter_algorithm_item_alter_page_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
