# Generated by Django 5.0.2 on 2024-04-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_database', '0024_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
